### PR TITLE
New joint analysis and report (v2.0.0)

### PR DESCRIPTION
**Pull request by preciserobot**
New joint analysis (readCount.R) for PoN and Batch normalisation methods. New report layout incorporating the results from both analysis strategies (exomeDepth.R).

Any RData files generated with this version (readcount files) are not compatible with previous versions. Existing panels of normals can be reused.

Merge into develop has been reviewed by Graeme Smith.

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)

### CODE REVIEW

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @natashapinto and @preciserobot)

___
*[`exomedepth/exomeDepth.R` line 145 at r2](https://reviewable.io/reviews/moka-guys/seglh-cnv/5#-NcgB2PA1obtIQsSrGdl:-NcgB2PA1obtIQsSrGdm:b-buelge) ([raw file](https://github.com/moka-guys/seglh-cnv/blob/9caa0ebdfe79d82f89231ac32da936aec1d1bb74/exomedepth/exomeDepth.R#L145)):*
> ```
>     ))
>   }
>   coverage.table<-coverage.df[which(coverage.df$coverage.median<limits$coverage & coverage.df$exon%in%exonnames),]
> ```

Just to check my understanding of this change - Rather than a summary of coverage for all reference samples combined we now get individual coverage details for each reference sample.
___
*[`exomedepth/exomeDepth.R` line 166 at r2](https://reviewable.io/reviews/moka-guys/seglh-cnv/5#-NcgBl3R4ljW65DWzJpF:-NcgBl3R4ljW65DWzJpG:bsjuoa2) ([raw file](https://github.com/moka-guys/seglh-cnv/blob/9caa0ebdfe79d82f89231ac32da936aec1d1bb74/exomedepth/exomeDepth.R#L166)):*
> ```
>   }
> 
>   #
> ```

Just checking my understanding of this change.  Originally you only needed to check the sex mismatch for a single test sample.  Th updated code is for scenarios where you need to check the sex mismatch for multiple reference samples (all samples in `refsamplenames`).
___
*[`exomedepth/readCount.R` line 108 at r2](https://reviewable.io/reviews/moka-guys/seglh-cnv/5#-NcgFzJECYrSDXulOXwM:-NcgFzJECYrSDXulOXwN:bs4jdhu) ([raw file](https://github.com/moka-guys/seglh-cnv/blob/9caa0ebdfe79d82f89231ac32da936aec1d1bb74/exomedepth/readCount.R#L108)):*
> ```
>     # if compatible normals, amend counts table
>     if (length(bam)>0) {
>         targets.same<-isTRUE(all.equal(counts.computed[,c(1:cmp.cols)], targets.imported))
> ```

Was this the cause of the bug? 

Original code uses the function `all.equal()`  to test if two objects are (nearly) equal. When the two objects are identical, `all.equal()` returns `TRUE`. However, if they are not identical, it does not simply return `FALSE`.  . Instead, it returns a character string describing the difference between the two objects.  By using `isTRUE()`, you ensure that `targets.same` is always either `TRUE` or `FALSE`.  Without `isTRUE()`, if the objects being compared by `all.equal()` are not identical, `targets.same` will be a character string, which could lead to unexpected behavior when used in a conditional statement.
___
*[`exomedepth/readCount.R` line 232 at r2](https://reviewable.io/reviews/moka-guys/seglh-cnv/5#-NcgHhvM7ZaQNeIv2NS5:-NcgHhvM7ZaQNeIv2NS6:b9mst9) ([raw file](https://github.com/moka-guys/seglh-cnv/blob/9caa0ebdfe79d82f89231ac32da936aec1d1bb74/exomedepth/readCount.R#L232)):*
> ```
> refsets<-lapply(testsamplenames, selectReferenceSet)
> names(refsets)<-testsamplenames
> ```

A change in formatting seems to have created a lot of irrelevant diffs.

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @Graeme-Smith and @preciserobot)

___
*[`exomedepth/exomeDepth.R` line 145 at r2](https://reviewable.io/reviews/moka-guys/seglh-cnv/5#-NcgB2PA1obtIQsSrGdl:-NcgSM3ZCgUzyX6xQu1t:bem4k5g) ([raw file](https://github.com/moka-guys/seglh-cnv/blob/9caa0ebdfe79d82f89231ac32da936aec1d1bb74/exomedepth/exomeDepth.R#L145)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Just to check my understanding of this change - Rather than a summary of coverage for all reference samples combined we now get individual coverage details for each reference sample.
</blockquote></details>

Each CNV coverage is plotted called against the PoN and against the batch 
___
*[`exomedepth/exomeDepth.R` line 166 at r2](https://reviewable.io/reviews/moka-guys/seglh-cnv/5#-NcgBl3R4ljW65DWzJpF:-NcgSZde35mY95oglbwy:b-24h48) ([raw file](https://github.com/moka-guys/seglh-cnv/blob/9caa0ebdfe79d82f89231ac32da936aec1d1bb74/exomedepth/exomeDepth.R#L166)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Just checking my understanding of this change.  Originally you only needed to check the sex mismatch for a single test sample.  Th updated code is for scenarios where you need to check the sex mismatch for multiple reference samples (all samples in `refsamplenames`).
</blockquote></details>

Now the sex check is performed on samples as references from the PoN and the batch

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: all files reviewed, 2 unresolved discussions (waiting on @preciserobot)

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: all files reviewed, 2 unresolved discussions (waiting on @preciserobot)

**Review by aledj2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: all files reviewed, 2 unresolved discussions (waiting on @preciserobot)

**Review by aledj2 — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 4 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: all files reviewed, 2 unresolved discussions (waiting on @preciserobot)

**Review by aledj2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/seglh-cnv/5)* status: all files reviewed, 2 unresolved discussions (waiting on @preciserobot)

**Comment by aledj2** [comment]
GS is on leave. I am merging this on the premise that GS has reviewed all docs - there isn't any outstanding requests for change.

**Pull request merged**
